import type { SurveyResponse } from "@/lib/types";

/** Column order aligned with R `sheet_columns` / Google Sheet header row. */
export function surveyResponseToSheetRow(row: SurveyResponse): (string | number | boolean)[] {
  return [
    row.session_id,
    row.submitted_at_utc,
    row.form_id,
    row.note_id,
    row.participant_email,
    row.participant_name,
    row.consent_acknowledgments_listed,
    row.demo_age,
    row.demo_race,
    row.demo_race_other,
    row.demo_hispanic,
    row.demo_education,
    row.demo_healthcare_bg,
    row.demo_recent_discharge,
    row.demo_confident_forms,
    row.demo_digital_comfort,
    row.demo_caregiver,
    row.demo_acknowledge_publication,
    row.hc_understand,
    row.hc_comfort,
    row.hc_clarity,
    row.hc_when_help,
    row.dc_understand,
    row.dc_comfort,
    row.dc_clarity,
    row.dc_when_help,
    row.faq_understand,
    row.faq_comfort,
    row.faq_clarity,
    row.faq_when_help,
    row.faq_unanswered,
  ];
}

export const SHEET_HEADER_ROW: string[] = [
  "session_id",
  "submitted_at_utc",
  "form_id",
  "note_id",
  "participant_email",
  "participant_name",
  "consent_acknowledgments_listed",
  "demo_age",
  "demo_race",
  "demo_race_other",
  "demo_hispanic",
  "demo_education",
  "demo_healthcare_bg",
  "demo_recent_discharge",
  "demo_confident_forms",
  "demo_digital_comfort",
  "demo_caregiver",
  "demo_acknowledge_publication",
  "hc_understand",
  "hc_comfort",
  "hc_clarity",
  "hc_when_help",
  "dc_understand",
  "dc_comfort",
  "dc_clarity",
  "dc_when_help",
  "faq_understand",
  "faq_comfort",
  "faq_clarity",
  "faq_when_help",
  "faq_unanswered",
];
